### ISSUE TITLE
Bug: Some index links don't work (see screenshots in new comments)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#158]
When clicking "What we're studying" index link, it anchors past the section title. see screenshots

![Screen Shot 2021-06-23 at 8 54 13 AM](https://user-images.githubusercontent.com/1387973/123129351-bebbcf80-d400-11eb-8027-69b366589708.png)
![Screen Shot 2021-06-23 at 8 54 09 AM](https://user-images.githubusercontent.com/1387973/123129360-c1b6c000-d400-11eb-9e90-31c8711bfe1c.png)

**Comment by chachasikes** [comment]
Note: This issue probably is due to calculation issues with accordion expansion.

**Comment by wrendo** [comment]
Broken index link

**Comment by wrendo** [comment]
The following 3 links don't click through

![Screen Shot 2021-07-13 at 8 51 36 AM](https://user-images.githubusercontent.com/1387973/125484557-ac18a731-b65a-4b0a-bb2b-d537834636c0.png)

![Screen Shot 2021-07-13 at 8 35 56 AM](https://user-images.githubusercontent.com/1387973/125484552-7382b062-a40b-43ff-a73f-2d36982cb2f4.png)

**Comment by chachasikes** [comment]
Have a patch for this to address it in the immediate term.

The rest of this discussion is about the underlying issue:

The disallowed lists are the unescaped characters that cannot be used in IDs/anchors/selectors (& ? # /\, etc)

What makes this an issue is that the allowed strings for anchor links "In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_)"

https://www.unicode.org/wg2/iso10646/edition5/charts/iso10646-5th-CodeCharts.pdf (Starting page 7)

You can see that it's all the Latin 1 characters that are allowed. This curly quote is technically in a miscellaneous area... but that's not the issue. 

The issue relates to translated content & all characters working in the anchors.

It would be nice to include based on a range.
`a-zA-Z0-9\u00A0-\u017F` - something like this should work 

(see also `a-zA-Z\u00A0-\u00D6\u00D8-\u00F6\u00F8-\u024F`)
(or a-zA-ZÀ-ÖÙ-öù-ÿĀ-žḀ-ỿ0-9)

There may be another function keeping javascript from picking up all the characters that are supposedly support. I would like us to solve for the language characters or, if we have to simplify it to a smaller a-z range, to be able to reference the exact technical issue,( since it would remove readability.)

Next step, see why diacritics block scroll.

**Comment by chachasikes** [comment]
Diacritics are ok, I had added an encodeURl wrapper, it was also needed when creating the anchor hash.

The full a-z ranges (with diacritics) may be same as using the unicode array, but will rewrite regex to include characters instead of excluding them and we should be good here.

p.s. Can't wait for multilingual test suite data.

**Comment by chachasikes** [comment]
Context note on why this is important: 

These are the anchors that are generated from the header. If a content editor did not create an anchor, the plain text of the header will be used, and that will be in any language.

---


This has a fix - I needed to add decoding for the recently added encoding. 

For now, keeping to just removing the unallowed characters for selectors.

* These are the encoders:
encodeURI & decodeURI
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI
Encodes all UTF8 characters except
Not Escaped:   `A-Z a-z 0-9 ; , / ? : @ & = + $ - _ . ! ~ * ' ( ) #`

* These are the CSS unallowed characters (Selector API is used with the anchors)
// !, ", #, $, %, &, ', (, ), *, +, ,, -, ., /, :, ;, <, =, >, ?, @, [, \, ], ^, `, {, |, }, and ~.


So:
1. Removing unallowed characters first
2. Encoding what's left
3. Decoding before setting the anchor hash

**Comment by chachasikes** [comment]
Tests are part of the original plan for this. We can pull from the covid-19 site and test with prior content in all our supported languages.

**Comment by chachasikes** [comment]
Also want us to fully understand risks in using these encoded links as shared URLs, bookmarks.

**Comment by chachasikes** [comment]
"W3C says URLs can only be sent over the Internet using the ASCII character-set." - and so, this is why we have percent encoding. 

Curly quote encoded in clipboard from browser (visually appears encoded)
http://wordpress.test:8888/about-us/scientific-research/#what-we%E2%80%99re-studying

The browser reformats it back & the reload works locally.

Trying with Arabic now...

**Comment by chachasikes** [comment]
(from covid-19, a real-life content example is business-and-employers-ar page has h2 tags)

**Comment by chachasikes** [comment]
Tested with Arabic characters & browser tests are good in Chrome.

Gonna port this component into our Storybook design system instance, which is a tool that will let us set up multilingual tests & not try to do edge case testing & QA with only a WP site.

**Comment by chachasikes** [comment]
We pushed this update in last release.

If bug still appears, either design system isn't synced (it should have been by now) or there are other underlying issues.

**Comment by chachasikes** [comment]
We finished this already. Is stuck in review phase.

**Comment by aaronhans** [comment]
I verified this is working on both monolith and headless. 

I am closing this now. @wrendo please reopen if necessary
