### ISSUE TITLE
Cosmetic: Header layout (engineering issue)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#244]
I believe we are not conforming to design for mobile header due to engineering issues on this. Let's explore a fix.

**Comment by wrendo** [comment]
DCC is ok if we use the circle logo stacked above left justified department text (font being used is Lexend. Arial is alternative if Lexend can't be used). 

Lexend ttf's are here: https://drive.google.com/drive/folders/1qSKJWl2HlVPCLbTncbEprWCmYHHnIar1?usp=sharing

See original figma design: https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=911%3A6941

Sample:

![Screen Shot 2021-07-26 at 1 58 15 PM](https://user-images.githubusercontent.com/1387973/127058269-9f267d90-2e74-4195-a92e-928b52f5fa1b.png)

**Comment by wrendo** [comment]
This is the design we should go with:
![image (1)](https://user-images.githubusercontent.com/1387973/128789514-aafdd35b-7173-4885-b282-780800615e6a.png)

Main font is Lexend
Font for "CALIFORNIA" is Arial

**Comment by aaronhans** [comment]
FYI I wasn't aware of this ticket and have a similar ticket here https://github.com/cagov/cannabis.ca.gov/issues/308

**Comment by aaronhans** [comment]
The design looks great on mobile when nothing is expanded but when the menu is expanded either the site name gets obscured or the menu opens below it which is a ways away from the hamburger that you clicked to open it.

Some screenshots from conversation with @kkoryaka 

Menu expanding and hiding the site name on cannabis:
<img width="304" alt="Screen Shot 2021-08-19 at 8 56 23 AM" src="https://user-images.githubusercontent.com/353360/130109760-9a769238-16f7-4a12-b23c-eb6dd166a403.png">

The same behavior on drought where there is no site logo is problematic
![Screen Shot 2021-08-19 at 9 04 05 AM copy](https://user-images.githubusercontent.com/353360/130109838-efb5d905-d14f-4de3-9a11-f8506c7799ee.jpg)

Looking for design advice here @adam-little to make sure we are covering all cases with expansion behavior.

Any version of this is tricky to implement because we probably can't order the HTML the way we things are displayed both on mobile and desktop so thanks for going over this with us again Adam. Will be cool to ratify this and then implement the optimal solution. Right now we have interestingly different patterns on https://cannabis.ca.gov and https://headless.cannabis.ca.gov

**Comment by adam-little** [comment]
The intention is the agency name/title to disappear when the menu is open. That way, the menu is closer to the menu/close links.

I put the menus for Cannabis and Drought [side by side on Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=4134%3A19437).

**Comment by aaronhans** [comment]
Here is where we are now https://headless.cannabis.ca.gov/ @kkoryaka fixed a lot of stuff to get this working.

I'd like to review the agency name disappearing request. Now that we can see the new hamburger placement in action it works better than I thought it would with the agency name still there. Thanks for reviewing this once more @adam-little @wrendo. 

Please flag any other things we need to fix with the header. We'll fix mobile issues in this ticket and address behaviors like when it should be sticky in separate tickets.

**Comment by kkoryaka** [comment]
@adam-little please review https://headless.cannabis.ca.gov/

**Comment by adam-little** [comment]
Thanks. The cosmetic issues have been fixed. 

Adding the footer links to the menu per the Figma design is not a high priority.

**Comment by chachasikes** [comment]
Done, closing.
