### ISSUE TITLE
Cosmetic: Main menu drop down blends into page indexes

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#247]
see screenshot

![Screen Shot 2021-07-13 at 12 50 05 PM](https://user-images.githubusercontent.com/1387973/125515928-e62e69b8-9699-42a2-ada1-b209d0f6bf74.png)

**Comment by adam-little** [comment]
Our proposed design was with dropshadows, which I think would address this concern. But dropshadows were de-prioritized because it added complexity.

Here is the original design:
![image](https://user-images.githubusercontent.com/69167298/126002104-2fb05416-494a-4162-b3d0-b3664232603b.png)

I believe the complexity resulted from the fact that the "tab" shape and "dropdown" shape are two separate divs and can not have a single dropshadow applied. 

Would this approach simplify things? Not having the background shape on the parent link.
![image](https://user-images.githubusercontent.com/69167298/126002360-211685c7-4ebb-49a0-baea-1c68b88804ec.png)

**Comment by adam-little** [comment]
@wrendo I think adding a dropshadow will prevent the two menus from blending. See above for a design solution that should make adding a dropshadow easier to implement.

**Comment by aaronhans** [comment]
Update is viewable on headless.cannabis.ca.gov

Sent link to Adam, he approved

PR is open for code review: https://github.com/cagov/cannabis.ca.gov/pull/270

**Comment by aaronhans** [comment]
This change is live on headless.cannabis.ca.gov

If we want to also implement it on the live site we need to apply the css shadowing to that codebase separately

**Comment by kkoryaka** [comment]
Updated monolith site custom css in CAWeb options. THis one is now done
