### ISSUE TITLE
Component: Per Page Feedback (informs DS)

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#48]
The per page feedback widget used on covid19.ca.gov is already a web component that accepts the url of the site being used and submits data to a scalable Azure CosmosDB via serverless endpoint.

This component has not yet been used on any other sites although it should work if some style issues are ironed out.

In one of the wireframe review sessions with the cannabis team they mentioned that this component should appear lower in the footer. It is placed at the desired location in the latest version of the wireframes.

This component was integrated into the WordPress site theme by Danny Guzman using a script include hack that added the web component js and then inserted the custom element into the footer. This was done without modifying the theme but allowed it to appear on all pages.

We need to modify the web component as required to make it more easily reusable and then work with the WordPress theme team again in the production site to integrate it into the footer.

**Comment by wrendo** [comment]
Seems like this needs to be scoped out further and broken down.

**Comment by aaronhans** [comment]
Ticket #5 contains the prerequisites to make the front and backend of the existing component usable on any site: https://github.com/cagov/design-system/issues/5

This ticket will track the integration of the latest version of the feedback component on the cannabis site.

When we include components that are fully encpasulated so can be added with a custom element and a script tag we should have a standard include method that allows versioning. 

This ticket should cover the following tasks:

- [ ] Create offsite component inclusion method - possibly ability to retrieve versioned js from CDN
- [ ] Document inclusion method 
- [ ] Integrate this element into cannabis production site, if necessary move into footer with no dependency client side script
- [ ] Scripts for multiple components should be combined and deferred when appropriate

**Comment by adam-little** [comment]
Here is design feedback. You can see detailed design in the ["Components and Styles" page on Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=439%3A3287).

- Add 5px corner radius to container
- Change background color to Cannabis secondary color (#2F4C2C)
- Move Submit button below form so that it does resize when form grows [see attached screenshot showing the problem]
- Make the top line of text for all states appear in the same position to avoid jarring movement. ("Did you find what you were looking for?" / "Great! What were you looking for today?" / "Thank you for your comments!")
- Change hover state color to #d5dbd5 (80% tint of default color) and underline text on hover

![image](https://user-images.githubusercontent.com/69167298/123150515-74524700-d430-11eb-8d1d-b73fb413db1d.png)

**Comment by aaronhans** [comment]
style fixes applied, packages published, bundles recreated, remaining css variable issue will require one more package bump

**Comment by aaronhans** [comment]
Remaining style fixes:
-   Remove bold treatment from text
-   Can we remove the color animation behavior when you hover on the buttons?

**Comment by aaronhans** [comment]
Last issue where the buttons wrapped weird on larger phones was fixed
